### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by bonovski** [zurb/foundation-sites#10910]
I get an error compiling foundation-sites with gulp with the babel-preset-env.
It worked fine with the babel-preset-es2015 before:

The complete error:

```
> Error: Couldn't find preset "es2015" relative to directory "/Users/peter/Sites/gulp-es6/node_modules/foundation-sites/dist/js" while parsing file: /Users/peter/Sites/gulp-es6/node_modules/foundation-sites/dist/js/npm.js
>     at /Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
>     at Array.map (<anonymous>)
>     at OptionManager.resolvePresets (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
>     at OptionManager.mergePresets (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
>     at OptionManager.mergeOptions (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
>     at OptionManager.init (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
>     at File.initOptions (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/index.js:212:65)
>     at new File (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/index.js:135:24)
>     at Pipeline.transform (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
>     at Babelify._flush (/Users/peter/Sites/gulp-es6/node_modules/babelify/index.js:26:24)
```

All other packages compile fine, though.

**Comment by ncoden** [comment]
Hi @bonovski

This should be resolved by https://github.com/zurb/foundation-sites/issues/10910: we should now export Foundation as transpiled UMD modules instead of ESM modules.

See also https://github.com/zurb/foundation-sites/pull/10903 and https://github.com/zurb/foundation-sites/pull/10911.

I'm closing this for now. Please reopen if it is not resolved in the next release.

**Comment by bonovski** [comment]
Hi, thanks for the links but that is not the solution with gulp.
I figured it out after some trial and error.

**You have to change the preset in "node_modules/foundation-sites/package.json" from _es2015_ to _env_.**

Hope that helps people with similar problems.
