### ISSUE TITLE
Tests crash on Node 11

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#11555]
## Description

See https://travis-ci.org/zurb/foundation-sites/jobs/445333501

```
> foundation-sites@6.4.3 test:javascript:transpile /home/travis/build/zurb/foundation-sites
> gulp sass:foundation --color && gulp test:transpile-js --color
fs.js:25
'use strict';
^
ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/travis/build/zurb/foundation-sites/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/home/travis/build/zurb/foundation-sites/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/travis/build/zurb/foundation-sites/node_modules/supercollider/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
```

This is a new issue on Node 11 and this cannot be reproduced on Node 10. This seems to come the `* > graceful-fs > natives@1.1.0` dependency. Fixed in `natives@1.1.1` (https://github.com/isaacs/natives/issues/14)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Note: this can be resolved with a simple `npm run relockdeps`. I'll do this tomorrow with an update of the devDependencies.
