### ISSUE TITLE
Error: Couldn't find preset "@babel/preset-env"

### ISSUE THREAD

**Issue by deckardd** [zurb/foundation-sites#11571]
## What should happen?

foundation-site should compile with gulp

## What happens instead?

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Couldn't find preset "@babel/preset-env" relative to directory "node_modules/foundation-sites/dist/js" while parsing file: node_modules/foundation-sites/dist/js/foundation.js
    at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
    at Babelify.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Babelify.emit (events.js:185:7)
    at prefinish (_stream_writable.js:505:12)
    at finishMaybe (_stream_writable.js:513:7)
```

## Your Environment

- Foundation version(s) used: 6.5.0

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please provide your package.json and gulpfile and .babelrc file.

You need `@babel/preset-env`.

**Comment by deckardd** [comment]
yeah, just locking to previous version instead
