### ISSUE TITLE
Code Elifecycle

### ISSUE THREAD

**Issue by jackiedao** [zurb/foundation-sites#11582]
Hi All,
 I have prolem when 'npm start'
and this: 
SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module._compile (/home/leodao/projects/vieplay/vieplay-html-v2/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.newLoader [as .js] (/home/leodao/projects/vieplay/vieplay-html-v2/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leodao/.npm/_logs/2018-11-11T23_31_53_997Z-debug.log

Node: v11.1.0
npm: v6.4.1

## What should happen?

...

## What happens instead?

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
@jackiedao Please fill the template correctly.
We cannot help you with so little information.

Closing. Please follow the template and describe your stack.
