### ISSUE TITLE
Can't run npm start anymore.

### ISSUE THREAD

**Issue by deryckoe** [zurb/foundation-sites#11723]
When I run npm start I get:

[10:54:15] Using gulpfile ~/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js
[10:54:15] Starting 'default'...
[10:54:15] Starting 'build'...
[10:54:15] Starting 'clean'...
[10:54:15] Finished 'clean' after 4.46 ms
[10:54:15] Starting 'styles'...
[10:54:15] Starting 'scripts'...
[10:54:15] Starting 'images'...
[10:54:15] Starting 'copy'...
[10:54:15] 'styles' errored after 52 ms
[10:54:15] TypeError: plugin.sass is not a function
    at styles (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js:115:22)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[10:54:15] 'build' errored after 58 ms
[10:54:15] 'default' errored after 61 ms
[10:54:15] The following tasks did not complete: scripts, images, copy
[10:54:15] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deryck/.npm/_logs/2019-03-18T13_54_15_911Z-debug.log

I tried to install gulp-sass without success. Delete node_modules and use npm install. The install was fine, however, npm start keeps giving error. Start happens suddenly. I did not update anything. 

Gulpfile function:
```
var gulp = require('gulp'),
    gutil = require('gulp-util'),
    browserSync = require('browser-sync').create(),
    filter = require('gulp-filter'),
    rimraf = require('rimraf'),
    plugin = require('gulp-load-plugins')();
```

```
// Compile Sass, Autoprefix and minify
function styles() {
    return gulp.src(SOURCE.styles)
        .pipe(plugin.plumber(function (error) {
            gutil.log(gutil.colors.red(error.message));
            this.emit('end');
        }))
        .pipe(plugin.sourcemaps.init())
        .pipe(plugin.sass({
            includePaths: ["node_modules/foundation-sites/scss", "node_modules/motion-ui/src"]
        }))
        .pipe(plugin.autoprefixer({
            browsers: [
                'last 2 versions',
                'ie >= 9',
                'ios >= 7'
            ],
            cascade: false
        }))
        .pipe(plugin.cssnano())
        .pipe(plugin.sourcemaps.write('.'))
        .pipe(gulp.dest(ASSETS.styles))
        .pipe(browserSync.stream())
}
```

package.json

```
{
  "name": "foundation-zurb-template",
  "version": "1.0.0",
  "description": "Official ZURB Template for Foundation for Sites.",
  "main": "gulpfile.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp build --production"
  },
  "author": "ZURB <foundation@zurb.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-preset-es2015": "^6.5.0",
    "browser-sync": "^2.11.0",
    "foundation-sites": "6.4.3",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.5.2",
    "gulp-cssnano": "^2.1.1",
    "gulp-filter": "^5.0.0",
    "gulp-imagemin": "^3.1.1",
    "gulp-jshint": "^1.11.0",
    "gulp-load-plugins": "^1.4.0",
    "gulp-newer": "^1.3.0",
    "gulp-plumber": "^1.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.8",
    "gulp-wp-pot": "^2.0.4",
    "jshint-stylish": "^2.0.0",
    "motion-ui": "^1.2.2",
    "rimraf": "^2.4.3",
    "what-input": "^4.1.3"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zurb/foundation-zurb-template.git"
  },
  "bugs": {
    "url": "https://github.com/zurb/foundation-sites/issues",
    "email": "foundation@zurb.com"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  },
  "private": true,
  "dependencies": {}
}
```

**Comment by DanielRuf** [comment]
> [10:54:15] TypeError: plugin.sass is not a function

Hi, this seems to be a problem with gulp-sass.
Please provide more details so we can reproduce this.

**Comment by DanielRuf** [comment]
> [10:54:15] TypeError: plugin.sass is not a function

Hi, it seem you do not have `gulp-sass` installed.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-zurb-template/blob/master/package.json#L35

**Comment by deryckoe** [comment]
Thanks Daniel.

I set package.json file again using the url you sent me.

After running npm install and npm start I get:

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> foundation-zurb-template@1.0.0 start /Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv
> gulp

[11:57:14] Using gulpfile ~/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js
[11:57:14] Starting 'default'...
[11:57:14] Starting 'build'...
[11:57:14] Starting 'clean'...
[11:57:14] Finished 'clean' after 4.42 ms
[11:57:14] Starting 'styles'...
[11:57:14] Starting 'scripts'...
[11:57:14] Starting 'images'...
[11:57:14] Starting 'copy'...
[11:57:14] The following tasks did not complete: scripts, images, copy
[11:57:14] Did you forget to signal async completion?
[11:57:14] 'styles' errored after 46 ms
[11:57:14] Error: Cannot find module 'gulp-sass' from '/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv'
    at Function.module.exports [as sync] (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/resolve/lib/sync.js:43:15)
    at requireFn (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/gulp-load-plugins/index.js:74:25)
    at Object.get [as sass] (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/gulp-load-plugins/index.js:117:41)
    at styles (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js:115:22)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[11:57:14] 'build' errored after 52 ms
[11:57:14] 'default' errored after 55 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deryck/.npm/_logs/2019-03-18T14_57_14_222Z-debug.log

Process finished with exit code 1
```

So, I'm in the same position :(

**Comment by DanielRuf** [comment]
There is written that gulp-sass is referenced but not (correctly) installed / found.

**Comment by DanielRuf** [comment]
Please do `console.log(plugin)` and check your node_modules.

**Comment by deryckoe** [comment]
I get:

{ babel: [Getter],
  cleanCss: [Getter],
  cli: [Getter],
  concat: [Getter],
  extname: [Getter],
  if: [Getter],
  imagemin: [Getter],
  postcss: [Getter],
  sass: [Getter],
  sourcemaps: [Getter],
  uglify: [Getter],
  plumber: [Getter] }

**Comment by DanielRuf** [comment]
Then `plugin.sass` should work. What else did you change? Please create a small repo which reproduces your issue.

**Comment by DanielRuf** [comment]
In general it would have been sufficient to run only `npm i gulp-sass --save-dev`.

**Comment by deryckoe** [comment]
Done!

I sent you an invitation to https://github.com/deryckoe/gulp-sass-issue

Thank you very much!

**Comment by DanielRuf** [comment]
Please do `npm i gulp-sass --save-dev`.
This should resolve your issue.

**Comment by deryckoe** [comment]
Solved partially. After that more errors come. gulp-cssnano, gulp-autoprefixer, gulp-jshint and now I'm getting (console.log(plugin) included):

**Error: Cannot find module 'jshint/src/cli'**

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> foundation-zurb-template@1.0.0 start /Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv
> gulp

[12:55:55] Using gulpfile ~/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js
[12:55:55] Starting 'default'...
[12:55:55] Starting 'build'...
[12:55:55] Starting 'clean'...
[12:55:55] Finished 'clean' after 3.95 ms
[12:55:55] Starting 'styles'...
[12:55:55] Starting 'scripts'...
[12:55:55] Starting 'images'...
[12:55:55] Starting 'copy'...
{ autoprefixer: [Getter],
  babel: [Getter],
  cleanCss: [Getter],
  cli: [Getter],
  concat: [Getter],
  cssnano: [Getter],
  extname: [Getter],
  filter: [Getter],
  if: [Getter],
  imagemin: [Getter],
  jshint: [Getter],
  plumber: [Getter],
  postcss: [Getter],
  sass: [Getter],
  sourcemaps: [Getter],
  uglify: [Getter] }
[12:55:57] 'scripts' errored after 1.78 s
[12:55:57] The following tasks did not complete: styles, images, copy
[12:55:57] Error: Cannot find module 'jshint/src/cli'
[12:55:57] Did you forget to signal async completion?
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[12:55:57] 'build' errored after 1.79 s
[12:55:57] 'default' errored after 1.79 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deryck/.npm/_logs/2019-03-18T15_55_57_639Z-debug.log

Process finished with exit code 1
```

A few days ago was working fine. I don't understand why the drastic change. :/

**Comment by DanielRuf** [comment]
Please run `npm i jshint --save-dev`.

**Comment by deryckoe** [comment]
:/

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> foundation-zurb-template@1.0.0 start /Users/deryck/Local Sites/mqv/app/public/wp-content/themes/mqv
> gulp

[13:01:05] Using gulpfile ~/Local Sites/mqv/app/public/wp-content/themes/mqv/gulpfile.js
[13:01:05] Starting 'default'...
[13:01:05] Starting 'build'...
[13:01:05] Starting 'clean'...
[13:01:05] Finished 'clean' after 4.51 ms
[13:01:05] Starting 'styles'...
[13:01:05] Starting 'scripts'...
[13:01:05] Starting 'images'...
[13:01:05] Starting 'copy'...
{ autoprefixer: [Getter],
  babel: [Getter],
  cleanCss: [Getter],
  cli: [Getter],
  concat: [Getter],
  cssnano: [Getter],
  extname: [Getter],
  filter: [Getter],
  if: [Getter],
  imagemin: [Getter],
  jshint: [Getter],
  plumber: [Getter],
  postcss: [Getter],
  sass: [Getter],
  sourcemaps: [Getter],
  uglify: [Getter] }
[13:01:07] The following tasks did not complete: styles, images, copy
[13:01:07] Did you forget to signal async completion?
[13:01:07] 'scripts' errored after 1.57 s
[13:01:07] Error in plugin "gulp-jshint"
Message:
    Invalid reporter
Details:
    domain: [object Object]
    domainThrown: true

[13:01:07] 'build' errored after 1.57 s
[13:01:07] 'default' errored after 1.57 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deryck/.npm/_logs/2019-03-18T16_01_07_134Z-debug.log

Process finished with exit code 1
```

**Comment by deryckoe** [comment]
I installed reporter. I will let you know asap if it's working.

**Comment by DanielRuf** [comment]
It is because of your gulpfile and missing dependencies. Please chdck the docs of gulp-jshint and jshint.

**Comment by DanielRuf** [comment]
I guess you also need `jshint-stylish`.

**Comment by DanielRuf** [comment]
`npm i jshint-stylish --save-dev`

**Comment by deryckoe** [comment]
I had to make a few more changes. Babel presets, Fundations Sites  and more but it's working now. 

Thank you very much Daniel for your infinite patience and kindness. You save my day.

Have a great day!
