### ISSUE TITLE
navigation.html and mobile-navigation.html partials missing

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7041]
`npm start` fails. Here is the console output:

```sh
/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216
    throw new _Exception2['default']('The partial ' + options.name + ' could n
          ^
Error: The partial navigation could not be found
    at Object.invokePartial (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:12:23)
    at ret (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Panini.module.exports [as render] (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/panini/lib/render.js:45:30)
    at DestroyableTransform.Transform._read (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/panini/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/panini/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/panini/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/colinmarshall/Projects/Testing/foundation-sites/node_modules/panini/node_modules/readable-stream/lib/_stream_writable.js:227:5)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/colinmarshall/.nvm/versions/node/v0.12.7/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! foundation-sites@6.0.1 start: `gulp`
npm ERR! Exit status 1
```

**Comment by colin-marshall** [comment]
Figured out this is happening because `docs/layout/default.html` calls for the `navigation.html` and `mobile-navigation.html` partials which don't exist. I'm guessing there are plans to add these in, it just didn't happen yet.

**Comment by colin-marshall** [comment]
Fixed by commit: https://github.com/zurb/foundation-sites/commit/571fa85d323d9c347a0ea5fa496677b16c7330dc
