### ISSUE TITLE
Zurb Template Update - SASS compilation places custom SASS at front of css file, foundation css after

### ISSUE THREAD

**Issue by mhair** [zurb/foundation-sites#8397]
**How can we reproduce this bug?**
1. Update to current Zurb template (with yml-based config) from previous version without yml/gulpfile.babel.js
2. NPM Start

**What did you expect to happen?**

Site would render the same

**What happened instead?**
Site rendering is mangled, due to the following statements in gulpfile I believe.

The includePaths being after the sourcemaps (with custom/overriding css) changes the cascade and design is rendered improperly. The include paths should come before the sourcemaps, but when I switch them and restart, I get the errors at bottom.

function sass() {
  return gulp.src('src/assets/scss/app.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      includePaths: PATHS.sass
    })
# 

C:\Users\mhair.ICS\Documents\Websites\foundation6temp.dev>npm start

> foundation-zurb-template@1.0.0 start C:\Users\mhair.ICS\Documents\Websites\foundation6temp.dev
> gulp

[14:57:59] Failed to load external module babel-register
[14:57:59] Requiring external module babel-core/register
[14:58:02] Using gulpfile ~\Documents\Websites\foundation6temp.dev\gulpfile.babel.js
[14:58:02] Starting 'default'...
[14:58:02] Starting 'build'...
[14:58:02] Starting 'clean'...
[14:58:02] Finished 'clean' after 5.97 ms
[14:58:02] Starting 'pages'...
[14:58:02] Starting 'sass'...
[14:58:02] Starting 'javascript'...
[14:58:02] Starting 'images'...
[14:58:02] Starting 'copy'...
[14:58:06] 'sass' errored after 3.68 s
[14:58:06] CssSyntaxError in plugin 'gulp-autoprefixer'
Message:
    C:\Users\mhair.ICS\Documents\Websites\foundation6temp.dev\src\assets\scss\app.scss:7:32: Unknown word
/\* ITCSS 'Settings Layer' */
@import '1-settings/settings'; // My _settings file which is consumed by the foundation/motion-ui mixins below
                               ^

Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[14:58:06] 'build' errored after 3.69 s
[14:58:06] 'default' errored after 3.69 s
[14:58:06] The following tasks did not complete: pages, javascript, images, copy
[14:58:06] Did you forget to signal async completion?

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\mhair.ICS\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-zurb-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-zurb-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-zurb-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mhair.ICS\Documents\Websites\foundation6temp.dev\npm-debug.log

C:\Users\mhair.ICS\Documents\Websites\foundation6temp.dev>

**Comment by gakimball** [comment]
How does the existence of sourcemaps affect the cascade? It's a separate `.css.map` file, right? Or even if it was an inline sourcemap, it's just one big CSS comment.

**Comment by mhair** [comment]
OK, this one was a wild goose chase, and I still can't explain how it happened. I've been using the zurb advanced template, and as you know I tested 6.2.0rc1. Basically, I noticed that even though I thought I had updated everything when the final 6.2 release came out, I still had references in code to 6.2.0rc1. I also wanted to be sure I had the latest Zurb Advanced Template, so to the best of my recall, my problems began when I did a bower update and npm update on everything, the both the framework and  the template. So when I reported the above, a changing of the cascade was my only reckoning of why the design rendering changed when I didn't recall making any major changes just prior to the update.

When I finally was able to get back to it, I noticed a lot of flex properties in my CSS, though I'm not using the flexbox grid. I then ran upon the announcement of the new $global-flexbox: variable in 6.2, and when I looked in my own settings override file, I found that indeed $global-flexbox was set to true. I'm completely baffled because I sure don't recall setting that to true, there would be no reason for me to since I have never intended to use flexbox on this project. I guess it could have been an absent-mind experiment just prior to the update, but....wierd! Is there anyway that you know of that this could have happened through an update? Feeling like I'm losing it on this one. :}

**Comment by colin-marshall** [comment]
@mhair did you try looking through your git history to see when `$global-flexbox` was added or to your settings file or when it was changed to true?

**Comment by mhair** [comment]
Unfortunately, I did not commit this code to git until after this had already occurred since I haven't done any serious development with 6.X due to its instability, at least on Windows, and generally regarding the build tools in the Zurb advanced template. So I have no history to compare it.

At this point, I'm planning to step away from their template and use the framework with prepros, prototyping directly in my Wordpress theme or otherwise just in whole/flat HTML pages. I guess I'll have to hold off on the JS side until the pre-compiled ES5 code is available.

**Comment by phifa** [comment]
i am too getting this error: 

```
[14:58:06] The following tasks did not complete: pages, javascript, images, copy
[14:58:06] Did you forget to signal async completion?
```

**Comment by russelpryor** [comment]
npm cache clearing, updating reinstalling and same with bower do not fix this error for me. I have this issue when I have the zurb template code upped to a git repository and then pull it down to another machine to work on.

**Comment by phifa** [comment]
I just got the issue again. Like @russelpryor I cannot resolve it by doing what I said above. Anybody?

**Comment by phifa** [comment]
I found out when I take out the javascript task in the gulpfile, it works: 

```
gulp.task('build',
 gulp.series(clean, gulp.parallel(pages, sass, images, copy), styleGuide));
```

So something is wrong with the javascript task I guess?

**Comment by DanielRuf** [comment]
Is this still happening?

**Comment by jonaslimads** [comment]
Yes, it has just happened to me. I have fresh installed a couple of minutes ago and when did npm run build, I got 
```sh
> foundation-emails-template@1.0.0 build /projects/goshare/emails/goshare
> gulp --production

[16:00:20] Failed to load external module @babel/register
[16:00:20] Requiring external module babel-register
[16:00:22] Using gulpfile /projects/goshare/emails/goshare/gulpfile.babel.js
[16:00:22] Starting 'default'...
[16:00:22] Starting 'build'...
[16:00:22] Starting 'clean'...
[16:00:22] Finished 'clean' after 8.73 ms
[16:00:22] Starting 'pages'...
[16:00:22] Finished 'pages' after 666 ms
[16:00:22] Starting 'sass'...
[16:00:27] Finished 'sass' after 4.61 s
[16:00:27] Starting 'images'...
[16:00:27] gulp-imagemin: Minified 0 images
[16:00:27] Finished 'images' after 98 ms
[16:00:27] Starting 'inline'...
Unhandled rejection TypeError: __html.replace is not a function
    at /projects/goshare/emails/goshare/node_modules/list-stylesheets/index.js:27:33
    at Array.forEach (<anonymous>)
    at encodeCodeBlocks (/projects/goshare/emails/goshare/node_modules/list-stylesheets/index.js:24:33)
    at encodeEntities (/projects/goshare/emails/goshare/node_modules/list-stylesheets/index.js:45:20)
    at module.exports (/projects/goshare/emails/goshare/node_modules/list-stylesheets/index.js:52:22)
    at module.exports (/projects/goshare/emails/goshare/node_modules/extract-css/index.js:11:16)
    at /projects/goshare/emails/goshare/node_modules/inline-css/lib/inlineContent.js:15:9
    at Promise._execute (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/promise.js:79:10)
    at inlineContent (/projects/goshare/emails/goshare/node_modules/inline-css/lib/inlineContent.js:8:12)
    at /projects/goshare/emails/goshare/node_modules/inline-css/index.js:31:9
    at Promise._execute (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/projects/goshare/emails/goshare/node_modules/bluebird/js/release/promise.js:79:10)
    at module.exports (/projects/goshare/emails/goshare/node_modules/inline-css/index.js:8:12)
    at DestroyableTransform._transform (/projects/goshare/emails/goshare/node_modules/gulp-inline-css/index.js:28:9)
    at DestroyableTransform.Transform._read (/projects/goshare/emails/goshare/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/projects/goshare/emails/goshare/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/projects/goshare/emails/goshare/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/projects/goshare/emails/goshare/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/projects/goshare/emails/goshare/node_modules/readable-stream/lib/_stream_writable.js:334:11)

[16:00:27] The following tasks did not complete: default, build, inline
[16:00:27] Did you forget to signal async completion?
```

**Comment by jonaslimads** [comment]
The problem seems to be on the list-stylesheets plugins. I went to node_modules/list-stylesheets/index.js and put a try-catch block around __html.replace, so

```javascript
                try {
                    __html = __html.replace(re, function (match) {
                        codeBlockLookup.push(match);
                        return 'EXCS_CODE_BLOCK_' + (codeBlockLookup.length - 1) + '_';
                    });
                } catch(e) {}
```

I'm not sure if this makes any difference on the output, but at least now I have an inline HTML.

**Comment by DanielRuf** [comment]
Please provide some info about your Node.js and npm versions.

**Comment by colin-marshall** [comment]
@jonaslimads you are on the wrong repo. Discussion for your issue belongs here: https://github.com/zurb/foundation-emails/issues/880

@DanielRuf I'm going to close this one out since it goes back to 2016. @phifa @russelpryor @mhair if you're still having issues feel free to reopen.

**Comment by russelpryor** [comment]
This problem was long gone, and I should have posted what fixed it for myself in case it's helpful:

I just cleaned up bower and npm...
`$ npm cache clean
$ npm install
$ bower install`

We're on a totally different version now and al is well.

**Comment by DanielRuf** [comment]
> This problem was long gone, and I should have posted what fixed it for myself in case it's helpful:
> 
> I just cleaned up bower and npm...
> $ npm cache clean $ npm install $ bower install
> 
> We're on a totally different version now and al is well.

Thanks for the feedback and letting us know that the issue was finally resolved =)
