### ISSUE TITLE
Foundation Watch / Npm Start / Gulp Fail

### ISSUE THREAD

**Issue by face0b1101** [zurb/foundation-sites#8573]
**How can we reproduce this bug?**

I'm not entirely sure how you may be able to reproduce this bug, that's part of the problem. I'm hoping someone may have already come across it and fixed it.

I am running Windows 10.
I have successfully installed foundation-cli via npm (globally), 
and have also tried cloning the zurb-foundation-template repo and running `npm install` + `bower install`

Whenever I run `foundation watch` (foundation-cli) or `npm start` I get the following output:

```
c:\foundationTest\testProject>npm start

> foundation-zurb-template@1.0.0 start c:\foundationTest\testProject
> gulp

[17:04:58] Requiring external module babel-core/register
[17:05:01] Using gulpfile c:\foundationTest\testProject\gulpfile.babel.js
[17:05:01] Starting 'default'...
[17:05:01] Starting 'build'...
[17:05:01] Starting 'clean'...
[17:05:01] Finished 'clean' after 43 ms
[17:05:01] Starting '<parallel>'...
[17:05:01] Starting 'pages'...
[17:05:01] Starting 'sass'...
[17:05:01] Starting 'javascript'...
[17:05:01] Starting 'images'...
[17:05:01] Starting 'copy'...
[17:05:03] Finished 'images' after 2.24 s
[17:05:06] Finished 'pages' after 5.56 s
[17:05:06] Finished 'sass' after 5.67 s
[17:05:07] Finished 'copy' after 5.76 s
[17:05:10] Finished 'javascript' after 8.7 s
[17:05:10] Finished '<parallel>' after 8.71 s
[17:05:10] Starting 'styleGuide'...
[17:05:10] Finished 'styleGuide' after 60 ms
[17:05:10] Finished 'build' after 8.82 s
[17:05:10] Starting 'server'...
[17:05:10] Finished 'server' after 75 ms
[17:05:10] Starting 'watch'...
true
[17:05:10] The following tasks did not complete: default, watch
[17:05:10] Did you forget to signal async completion?

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Will\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-zurb-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-zurb-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-zurb-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\foundationTest\testProject\npm-debug.log
```

I have completely uninstalled and reinstalled node, npm & git several times. I have tried a variety of different directories.

 Every time I do a fresh install I get the same error.

**What did you expect to happen?**

I expected the gulp watch to run, and for browser-sync to load a copy of the default foundation page in my browser. 

**What happened instead?**

I got the above output. Browser-Sync fails to load, and watch fails to run when files are updated.
The dist folder is successfully created fresh each time, however.

I appreciate that this a problem not so much about foundation, but with the development tools. I have very little experience with gulp, so I am at a bit of a loss on how to correct this error. 

I have posted the verbose error log on [pastebin](http://pastebin.com/G2kfgLwb)
I have also asked this question on the [foundation forum](http://foundation.zurb.com/forum/posts/39391-foundation-watch-fails-windows)

I'd appreciate any advice!

**Comment by mhair** [comment]
I'm having pretty close the same result. Note that when I do npm start with the default file structure as created by the foundation new install (using the zurb template), it runs without error. However, when I rename the "src" folder and paste in my "src" folder from previous attempts to work with the zurb template, that's when I start generating errors. Trace below:

PS C:\Users\mhair.ICS\documents\websites\foundation6temp.dev> npm start

> foundation-zurb-template@1.0.0 start C:\Users\mhair.ICS\documents\websites\foundation6temp.dev
> gulp

[15:18:34] Failed to load external module babel-register
[15:18:34] Requiring external module babel-core/register
[15:18:35] Using gulpfile ~\documents\websites\foundation6temp.dev\gulpfile.babel.js
[15:18:35] Starting 'default'...
[15:18:35] Starting 'build'...
[15:18:35] Starting 'clean'...
[15:18:35] Finished 'clean' after 14 ms
[15:18:35] Starting 'pages'...
[15:18:35] Starting 'sass'...
[15:18:35] Starting 'javascript'...
[15:18:35] Starting 'images'...
[15:18:35] Starting 'copy'...
[15:18:37] Finished 'sass' after 2.64 s
[15:18:38] Finished 'pages' after 3.15 s
[15:18:39] Finished 'copy' after 4.1 s
[15:18:39] 'javascript' errored after 4.47 s
[15:18:39] SyntaxError in plugin 'gulp-babel'
Message:
    C:\Users\mhair.ICS\documents\websites\foundation6temp.dev\src\.babelrc: Error while parsing JSON - Unexpected ''
[15:18:39] 'build' errored after 4.49 s
[15:18:39] 'default' errored after 4.49 s
[15:18:39] The following tasks did not complete: images
[15:18:39] Did you forget to signal async completion?

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhair.ICS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin
\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-zurb-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-zurb-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-zurb-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mhair.ICS\documents\websites\foundation6temp.dev\npm-debug.log
PS C:\Users\mhair.ICS\documents\websites\foundation6temp.dev>

It starts off with failure to load an external module, but doesn't identify which. I read elsewhere that this is likely the babel module, so I tried the following install to get rid of that error message.
npm install gulp-babel babel-preset-es2015 --save-dev
It didn't resolve it.

Then further down when it comes to the javascript task, you see "SyntaxError in plugin 'gulp-babel'. My dist folder is built, but there is no app.js in the js folder.

Later it complains about signalling async completion, which I've not seen any instruction for in the installation docs.

So this is pretty much par for the course in my experience on Windows 7. Again I have to ask if this was tested on Windows 7, or Windows in general. I would certainly assume/hope, but....? It could just be my and a number of others Windows configurations, but from what I've seen in many many forums, node/npm on Windows is a rats nest without much hope for consistency. This makes Zurb's dependence on it to be extremely problematic. Even going to "prepros" I found that it choked due to the babel dependency. I will try prepros again since 6.2.1 is supposed to have precompiled ES5 javascript.

Zurb, please chime in here if you have any bones for the poor Windows have nots. It's not a happy scene, and hasn't been all the way along as you know.

**Comment by colin-marshall** [comment]
@mhair: What are the specific differences between the two `src ` directories that you swap out? I am not sure about Windows tests, @kball & @rafibomb would be the ones to speak on that. 

@mhair, @face0b1101: Can you run `gulp -v` for me please and paste the results?

**Comment by face0b1101** [comment]
@colin-marshall sorry for not replying sooner. Work has me away from my machine, when I can get a moment I'll get back to you. 

Off the top of my head I think the version is 1.2.1 for the cli, and 4 beta 2 for the other version. Don't know if that helps.

**Comment by face0b1101** [comment]
@colin-marshall, you asked this question on the foundation forum:

> 
> @Will what happens when you change the default task to run `server` and `watch` in parallel?
> 
> // Build the site, run the server, and watch for file changes
> gulp.task('default',
>   gulp.series('build', gulp.parallel(server, watch)));

The answer is, I get the following (very similar) output:
```
> foundation-zurb-template@1.0.0 start C:\Users\Will\Websites\foundationSites\testProject
> gulp

[16:13:26] Failed to load external module babel-register
[16:13:26] Requiring external module babel-core/register
[16:13:40] Using gulpfile ~\Websites\foundationSites\testProject\gulpfile.babel.js
[16:13:40] Starting 'default'...
[16:13:40] Starting 'build'...
[16:13:40] Starting 'clean'...
[16:13:41] Finished 'clean' after 31 ms
[16:13:41] Starting 'pages'...
[16:13:41] Starting 'sass'...
[16:13:41] Starting 'javascript'...
[16:13:41] Starting 'images'...
[16:13:41] Starting 'copy'...
[16:13:48] Finished 'images' after 7.34 s
[16:13:51] Finished 'pages' after 10 s
[16:13:51] Finished 'sass' after 10 s
[16:13:51] Finished 'copy' after 10 s
[16:13:53] Finished 'javascript' after 13 s
[16:13:53] Starting 'styleGuide'...
[16:13:53] Finished 'styleGuide' after 72 ms
[16:13:53] Finished 'build' after 13 s
[16:13:53] Starting 'server'...
[16:13:53] Starting 'watch'...
[16:13:53] Finished 'server' after 100 ms
true
[16:13:53] The following tasks did not complete: default, <parallel>, watch
[16:13:53] Did you forget to signal async completion?
Error: foundation-zurb-template@1.0.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\Will\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\lib\util
s\lifecycle.js:217:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at ChildProcess.<anonymous> (C:\Users\Will\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\lib\util
s\spawn.js:24:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

notice the additional failure - <parallel>

**Comment by will** [comment]
Normally i'd say you have to join the threads, but i think this is all js
stuff so, idk promises? I don't really know JavaScript sorry.

**Comment by mhair** [comment]
@colin-marshall 
Here is the output from gulp -v

[11:49:03] CLI version 1.2.1
[11:49:03] Local version 3.9.1
PS C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress>

I followed instructions elsewhere to install the gulp cli at the global level, and gulp locally. I've tried both this version of gulp, and the 4.0 alpha 2.

Regarding your question above about what was different about my src folder, it basically just contains multiple layout/partial/pages the way the template is intended to be used. But there is a twist here that I'm not sure I have an explanation for. 

I'm currently testing 6.2.1 code in two different ways. 1, the output from above where I was getting the error reported, is a zurb template based prototyping set up. Since I reported the above, the project is now compiling properly and not complaining about anything. What changed?, I changed the config.yml statements to point to the precompiled js, such as this:
 - "bower_components/foundation-sites/dist/plugins/foundation.abide.js"
However, none of the javascript is working per dropdown menus that aren't firing. I have yet to determine why.

Meanwhile, I had already returned to my foundationpress 2.5 (based on foundation 6) project to do a bower update in hopes that it would run with 6.2.1 foundation. npm run watch did not compile and I get the following output.

PS C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress> npm run
 watch

> foundationpress@2.6.1 watch C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\them
es\foundationpress
> gulp

[11:45:15] Using gulpfile ~\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress\gu
lpfile.js
[11:45:15] Starting 'clean'...
[11:45:15] Starting 'clean:javascript'...
[11:45:15] 'clean:javascript' errored after 139 µs
[11:45:15] ReferenceError: del is not defined
    at Gulp.<anonymous> (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\fo
undationpress\gulpfile.js:235:10)
    at module.exports (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foun
dationpress\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content
\themes\foundationpress\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content
\themes\foundationpress\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\th
emes\foundationpress\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundati
onpress\node_modules\run-sequence\index.js:88:16)
    at runSequence (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundat
ionpress\node_modules\run-sequence\index.js:99:2)
    at Gulp.<anonymous> (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\fo
undationpress\gulpfile.js:229:3)
    at module.exports (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foun
dationpress\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content
\themes\foundationpress\node_modules\orchestrator\index.js:273:3)
[11:45:15] 'clean' errored after 3.61 ms
[11:45:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'clean:javascript'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhair.ICS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin
\\npm-cli.js" "run" "watch"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.1 watch: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundationpress@2.6.1 watch script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundationpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundationpress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundationpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpres
s\npm-debug.log
PS C:\Users\mhair.ICS\documents\websites\foundationpress6.boardofed.idaho.dev\wp-content\themes\foundationpress> 

I have not been able to figure this one out, even using node-debug and a similar node debugging feature of phpstorm. This is the foundationpress version of the gulpfile, not the new yaml based one in Foundation 6.2.1 (and 6.2). So this may be the reason for this. I also tried using this setup with the precompiled js but got the same error.

[13:18:11] Error in plugin 'run-sequence'
Message:
    An error occured in task 'clean:javascript'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhair.ICS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin
\\npm-cli.js" "run" "watch"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundationpress@2.6.1 watch: `gulp`

The only bright spot here is that I then dove deep into translating the gulpfile instructions to something that prepros could work with and I now, for the first time since starting with foundation 6.x, have a fully functioning codebase. But it required taking the gulp/node workflow completely out of the picture. Again, your FoundationPress Grunt-based workflow also worked.

Long story but I felt I needed to put it out there considering how much grief I've been spilling in the forums.

@colin-marshall , if there is anything in these errors that triggers any ideas, please let me know as I'm still curious if I can get the gulp workflow going, but my pace dedicated to it will slow to outside work hours.

**Comment by colin-marshall** [comment]
@mhair: `ReferenceError: del is not defined` would either mean that you don't have `var del = require('del')` in your `gulpfile.js`, you did not run `npm install`, or the `del` package is missing from `package.json`.

**Comment by face0b1101** [comment]
Desperate times, desperate measures.

I could not find a way to rectify this problem. It seems to be an error specific to my particular Windows installation. I seemed to be having a few odd errors in other applications also.
Therefore, unable to fix the problem, I decided to refresh Windows 10...

...** Everything now works as expected.**

So to anyone else who stumbles accross this thread with this error, I recommend you just start again with a fresh copy of Windows. There is probably a way to solve it, but it was much easier to just go for a fresh install.

Thanks to everyone who chipped in with suggestions.

**Comment by mhair** [comment]
@colin-marshall : I checked all of those things prior, and again just verified, including that the specific file mentioned in the clean:javascript task was there...it is. Plus I did an npm install del --save-dev just for good measure. Any other ideas?

**Comment by colin-marshall** [comment]
@mhair I'm running out of ideas. Have you tried installing a Node version manager? There's a few for Windows. It allows you to have multiple installs of different versions of Node and switch between them. I would suggest trying this and see if having isolated Node installations with a version manager makes something "work" that wasn't before.

Here's what looks like the most popular one:
https://github.com/coreybutler/nvm-windows

Have you tried any other Win7 computers to see if it's only an issue on your install?
