### ISSUE TITLE
[Starter Projects] ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by paoloantinori** [zurb/foundation-sites#8881]
**How can we reproduce this bug?**
1. foundation new
2. chose basic template
3. npm start

**What did you expect to happen?**
Not to fail

**What happened instead?**

```
12:10:53 (..teatro/html/teatro)$ npm start

> foundation-sites-template@1.0.0 start /data/user/documents/Personal/teatro/html/teatro
> gulp

[12:11:38] Using gulpfile /data/user/documents/Personal/teatro/html/teatro/gulpfile.js
[12:11:38] Starting 'sass'...

/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21)
    at DestroyableTransform._transform (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/data/user/documents/Personal/teatro/html/teatro/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:95:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by heyflynn** [comment]
I had the same problem. My node/npm was outdated. Try upgrading then start a new project

**Comment by JeremyEnglert** [comment]
No response. Closing.
