### ISSUE TITLE
Minification failure- unexpected character, Foundation Core JS

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#9057]
Running Codekit on a Mac and getting this minification error:

```
Minification failed:

Parse error at ../../bower_components/foundation-sites/js/foundation.core.js:56,29
Unexpected character '`'
Error
    at new JS_Parse_Error (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at parse_error (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1647:9)
    at Object.next_token [as input] (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1912:9)
    at next (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2012:25)
    at subscripts (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2695:13)
    at subscripts (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2676:20)
    at subscripts (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2676:20)
    at expr_atom (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2552:20)
    at maybe_unary (eval at <anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)
```

Looks like the character ` is being used instead of ' throughout the file.

**Comment by daveromsey** [comment]
Sounds like a problem with Codekit and Babel. [Precompiled JS is available as an alternative.](https://github.com/zurb/foundation-sites/issues/8419)

**Comment by colin-marshall** [comment]
@dlewand691 I'm closing this as @daveromsey's answer points out the issue. Please feel free to reopen if you have further questions.

**Comment by dub** [comment]
Deploying to Heroku will also throw this error.
