### ISSUE TITLE
Gulp fsevents compatibility bug 

### ISSUE THREAD

**Issue by vikcon** [zurb/foundation-sites#9206]
Foundation New command eventually fails, with error Node modules not installed,
After npm install in the site folder,
it give following error

`npm WARN optional dep failed, continuing fsevents@1.0.14`
and some module list.
After
 `foundation watch `

> [21:44:58] Requiring external module babel-register
> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'lodash/cloneDeep'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\wamp\www\vik\node_modules\babel-preset-es2015\node
> _modules\babel-plugin-transform-es2015-classes\node_modules\babel-template\lib\i
> ndex.js:57:18)
>     at Module._compile (module.js:409:26)
>     at Module._extensions..js (module.js:416:10)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\wamp\www\vik\
> node_modules\babel-register\lib\node.js:154:7)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>  Error: foundation-zurb-template@1.0.0 start: `gulp`
> Exit status 1
>     at EventEmitter.<anonymous> (C:\Users\Vikram\AppData\Roaming\npm\node_module
> s\foundation-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
>     at emitTwo (events.js:87:13)
>     at EventEmitter.emit (events.js:172:7)
>     at ChildProcess.<anonymous> (C:\Users\Vikram\AppData\Roaming\npm\node_module
> s\foundation-cli\node_modules\npm\lib\utils\spawn.js:24:14)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:829:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 
> 

My setup is
Windows 7
Node v4.5.0
NPM v2.15.9
Foundation-cli newly installed

I have earlier used foundation SASS successfully here, almost two months back.

- [ I believe it is gulp issue Windows specific. ]

**Update**
Gulp discussion says, it shouldn't be the cause. Something else is creating problem. 

Eventually while searching I found similar issues here
[https://github.com/mgechev/angular2-seed/issues/711](https://github.com/mgechev/angular2-seed/issues/711)
[https://github.com/gulpjs/gulp/issues/1810](https://github.com/gulpjs/gulp/issues/1810)

**Comment by vikcon** [comment]
Manually updated lodash.clonedeep, babel-register, babylon with --save.
now build is working. Not sure what went wrong.
