### ISSUE TITLE
Foundation Sites Gulp Error

### ISSUE THREAD

**Issue by npapazian** [zurb/foundation-sites#9907]
I pulled down a copy of this repo (https://github.com/zurb/foundation-sites.git) and am getting a gulp error trying to run the project. I installed all the node packages, but when I go to run npm start, the gulp task starts but errors out after about 5 seconds. It seems to be the 'docs:all' task that is the culprit, but I can't figure out what is wrong. 

**Steps to reproduce:**
1. Clone this repo
2. run npm install
3. run npm start

**Here's my npm-debug.log file:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Nathan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.5.3
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundation-sites@6.3.1~prestart: foundation-sites@6.3.1
6 silly lifecycle foundation-sites@6.3.1~prestart: no script for prestart, continuing
7 info lifecycle foundation-sites@6.3.1~start: foundation-sites@6.3.1
8 verbose lifecycle foundation-sites@6.3.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle foundation-sites@6.3.1~start: PATH: C:\Users\Nathan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Nathan\Downloads\foundation-sites-develop\foundation-sites-develop\node_modules\.bin;C:\Python27;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\ProgramData\Lenovo\ReadyApps;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\Nathan\.dnx\bin;C:\Users\Nathan\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle foundation-sites@6.3.1~start: CWD: C:\Users\Nathan\Downloads\foundation-sites-develop\foundation-sites-develop
11 silly lifecycle foundation-sites@6.3.1~start: Args: [ '/d /s /c', 'gulp' ]
12 silly lifecycle foundation-sites@6.3.1~start: Returned: code: 1  signal: null
13 info lifecycle foundation-sites@6.3.1~start: Failed to exec start script
14 verbose stack Error: foundation-sites@6.3.1 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Nathan\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Nathan\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid foundation-sites@6.3.1
16 verbose cwd C:\Users\Nathan\Downloads\foundation-sites-develop\foundation-sites-develop
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nathan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.2.4
20 error npm  v3.5.3
21 error code ELIFECYCLE
22 error foundation-sites@6.3.1 start: `gulp`
22 error Exit status 1
23 error Failed at the foundation-sites@6.3.1 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundation-sites package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundation-sites
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundation-sites
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kball** [comment]
This is odd... maybe a windows issue? @abdullahsalem can you take a look?

**Comment by Deckluhm** [comment]
> This is odd... maybe a windows issue?

I wasn't able to reproduce the error on Linux (same version of Node / NPM).

**Comment by npapazian** [comment]
Seems to be working for me now.  I'll close it.
