### ISSUE TITLE
Requiring external module babel-register module.js:471 throw err;

### ISSUE THREAD

**Issue by TheCodingSmith** [zurb/foundation-sites#9918]
#### How to reproduce this bug:
1. On Windows 10
2. Open Bash in root directory
3. Run `npm start`
#### What should happen:

It should run the server

#### What happened instead:

$ npm start

> foundation-zurb-template@1.0.0 start C:\Users\death\Documents\Projects\coding-smith source code
> gulp

[17:30:11] Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module './fs.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\death\Documents\Projects\coding-smith source code\node_modules\graceful-fs\polyfills.js:1:10)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\death\Documents\Projects\coding-smith source code\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\death\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-zurb-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-zurb-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-zurb-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\death\Documents\Projects\coding-smith source code\npm-debug.log

$ node -v
v6.9.4

$ npm -v
4.1.1

$ gulp -v
[19:33:22] Requiring external module babel-register
[19:33:22] CLI version 1.2.2
[19:33:22] Local version 4.0.0-alpha.2

**Comment by TheCodingSmith** [comment]
To note. 
The server was running fine. I made a change in my src/data/**.json file, reloaded the server and got this. 
I since then have done a `git checkout .` and I still get this error. Nothing else has changed.
